name: 'GS64 Components Loading'
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
   component-loading-3_7_0:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        load-spec:
          - Deployment
    name: GS64 v3.7.0 + ${{ matrix.load-spec }}
    steps:
      - uses: actions/checkout@v4
      - name: Load component in image
        uses: ba-st-actions/gs64-ci@v2
        with:
          project_name: 'Aconcagua'
          load_spec: 'Aconcagua-${{ matrix.load-spec }}'
   component-loading-3_7_1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        load-spec:
          - Deployment
    name: GS64 v3.7.1 + ${{ matrix.load-spec }}
    steps:
      - uses: actions/checkout@v4
      - name: Load component in image
        uses: ba-st-actions/gs64-ci@v3
        with:
          project_name: 'Aconcagua'
          load_spec: 'Aconcagua-${{ matrix.load-spec }}'
